# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Tallybook' do
  use_frameworks!

  # Pods for Tallybook
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'FirebaseFirestoreSwift'

  target 'TallybookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TallybookUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
    end
  end
end
