# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Tallybook' do
  use_frameworks!

  # Pods for Tallybook
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  target 'TallybookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TallybookUITests' do
    # Pods for testing
  end

end
