# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tallybook' do
  use_frameworks!

  # Pods for Tallybook

  target 'TallybookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TallybookUITests' do
    # Pods for testing
  end

end
